theme: jekyll-theme-slate
title: Kacper Wardynski
description: Under Construction | Projects Coming Soon! <br> [Back Home](https://kwardynski.github.io/)
defaults:
  - scope:
      path: ""
    values:
      layout: default
